### ISSUE TITLE
Warnings about the number of centroids used for clustering

### ISSUE THREAD

**Issue by martiansideofthemoon** [krishnap25/mauve#4]
Dear authors, thanks for release the MAUVE metrics in such an easy-to-use repository! 

I had a quick question about a warning I get each time I run MAUVE using the command provided in the README,

```
mauve_out = mauve.compute_mauve(p_text=gen_seqs, q_text=gold_seqs, device_id=0, max_text_length=768, verbose=False)
```
This nearly always gives me a warning of the form,

```
WARNING clustering 9286 points to 464 centroids: please provide at least 18096 training points
```

Is this something I need to worry about? Should I set `num_buckets` manually?

Thanks again for your excellent project!

**Comment by krishnap25** [comment]
Hi @martiansideofthemoon, 

I wouldn't worry about this warning. It comes from the k-means implementation of [faiss](https://github.com/facebookresearch/faiss). 

The details of the warning are given [here](https://github.com/facebookresearch/faiss/wiki/FAQ#can-i-ignore-warning-clustering-xxx-points-to-yyy-centroids) as: 
```
n < min_points_per_centroid * k: this produces the warning above. 
It means that usually there are too few points to reliably estimate the centroids. 
This may still be ok if the dataset to index is as small as the training set.
```

Since we do not care about estimating the centroids, we ignore this warning. We will post an update suppressing this warning soon. 

Best, 
Krishna
